PACKAGE_NAME="ethercat"
PACKAGE_VERSION="1.7.1"

MAKE[0]="make"
CLEAN="make clean"

BUILT_MODULE_NAME[0]="ec_master"
BUILT_MODULE_LOCATION[0]="master/"
DEST_MODULE_LOCATION[0]="/kernel/drivers/ethercat"

BUILT_MODULE_NAME[1]="ec_generic"
BUILT_MODULE_LOCATION[1]="devices/"
DEST_MODULE_LOCATION[1]="/kernel/drivers/ethercat"

BUILT_MODULE_NAME[2]="ec_igb"
BUILT_MODULE_LOCATION[2]="devices/igb/"
DEST_MODULE_LOCATION[2]="/kernel/drivers/ethercat"

BUILT_MODULE_NAME[3]="ec_e1000"
BUILT_MODULE_LOCATION[3]="devices/e1000/"
DEST_MODULE_LOCATION[3]="/kernel/drivers/ethercat"

BUILT_MODULE_NAME[4]="ec_igc"
BUILT_MODULE_LOCATION[4]="devices/igc/"
DEST_MODULE_LOCATION[4]="/kernel/drivers/ethercat"

BUILT_MODULE_NAME[5]="ec_r8169"
BUILT_MODULE_LOCATION[5]="devices/r8169/"
DEST_MODULE_LOCATION[5]="/kernel/drivers/ethercat"

BUILT_MODULE_NAME[6]="ec_ccat"
BUILT_MODULE_LOCATION[6]="devices/ccat/"
DEST_MODULE_LOCATION[6]="/kernel/drivers/ethercat"

BUILT_MODULE_NAME[7]="ec_e100"
BUILT_MODULE_LOCATION[7]="devices/"
DEST_MODULE_LOCATION[7]="/kernel/drivers/ethercat"

BUILT_MODULE_NAME[8]="ec_8139too"
BUILT_MODULE_LOCATION[8]="devices/"
DEST_MODULE_LOCATION[8]="/kernel/drivers/ethercat"

AUTOINSTALL="yes"
