#!/bin/bash
set -e

if [ "$1" = "remove" ] || [ "$1" = "upgrade" ] || [ "$1" = "deconfigure" ]; then
    if command -v systemctl >/dev/null 2>&1 && [ -d "/run/systemd/system" ]; then
        systemctl stop ethercat.service >/dev/null 2>&1 || true
        systemctl stop ethercat-first-boot.service >/dev/null 2>&1 || true
    fi
fi

exit 0
